name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # Ou 'master' se estiver usando essa branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Criar diretório público e copiar arquivos
        run: |
          mkdir -p public
          echo "const GOOGLE_CLIENT_ID = '${{ secrets.GOOGLE_CLIENT_ID }}';" > public/config.js
          cp index.html script.js imagem.png perfil1.png perfil2.png public/

      - name: Configurar e publicar no GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: public

      - name: Implantar no GitHub Pages
        uses: actions/deploy-pages@v1
